# Site settings
title: Clear Air Turbulence
email: fractos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Adam's coding blog at GitHub.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fractos.github.io" # the base hostname & protocol for your site
twitter_username: fractos
github_username:  fractos

# Build settings
markdown: kramdown
